# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 14:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_linkedin_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('is_incorporated', models.BooleanField(default=False)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('investor_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('stage', models.CharField(choices=[('Pre-seed', 'Pre-seed'), ('Seed', 'Seed'), ('Post-seed', 'Post-seed')], default='Pre-seed', max_length=20)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('funding_requirement', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='document')),
                ('copa_required', models.BooleanField(default=False)),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StartupTeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startup.Startup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
