export const authConstant = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    AUTH_REMOVE_TOKEN: 'AUTH_REMOVE_TOKEN',
    AUTH_SET_TOKEN: 'AUTH_SET_TOKEN',

}