export const authConstant = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    AUTH_REMOVE_TOKEN: 'AUTH_REMOVE_TOKEN',
    AUTH_SET_TOKEN: 'AUTH_SET_TOKEN',
    SIGNUP_USER: 'SIGNUP_USER',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',
}