# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 14:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('investor_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('stage', models.CharField(choices=[('Pre-seed', 'Pre-seed'), ('Seed', 'Seed'), ('Post-seed', 'Post-seed')], default='Pre-seed', max_length=20)),
                ('investment_size', models.IntegerField(choices=[(1, 'Less than US $10,000'), (2, 'US $ 10,000 - 25,000')], default=1)),
                ('expected_deals_per_year', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
